services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    container_name: slava_tz_php_container
    volumes:
      - ./src:/var/www/laravel
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    user: ${MY_UID}:${MY_GID}
    environment:
      - QUEUE_CONNECTION=redis
      - MY_UID=${MY_UID}
      - MY_GID=${MY_GID}
    networks:
      - default
    depends_on:
      - redis

  queue-worker:
    build:
      context: .
      dockerfile: dockerfiles/php.Dockerfile
    command: ["php", "/var/www/laravel/artisan", "queue:listen", "--timeout=180"]
    volumes:
      - ./src:/var/www/laravel
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/24"
